version: "2.0"

services:
  springboot-jakarta-example-demo:
    image: 'your-company.harbor.com/admin-template/admin-template-boot:2025.04.09-SNAPSHOT'
    restart: always
    container_name: admin-template-boot
    ports:
      - "18080:8080"
    volumes:
      - "/d/data/app/logs:/opt/app/logs"
    environment:
      - JAVA_OPTS=-server -Xms512m -Xmx1g
      - spring.profiles.active=test
    mem_limit: 2048M
    logging:
      options:
        max-size: 100m
    networks:
      - devops
networks:
  devops:
    external:
      name: devops01